# Generated by Django 5.2.6 on 2025-09-19 21:49

import authapp.models
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_badge_user_created_at_user_profile_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userbadge",
            name="badge",
        ),
        migrations.RemoveField(
            model_name="userbadge",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userstats",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="badge",
            options={"ordering": ["badge_type", "name"]},
        ),
        migrations.AlterModelOptions(
            name="test",
            options={"ordering": ["category", "name"]},
        ),
        migrations.RemoveField(
            model_name="test",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="test",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="test",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="test",
            name="score",
        ),
        migrations.RemoveField(
            model_name="test",
            name="status",
        ),
        migrations.RemoveField(
            model_name="test",
            name="test_type",
        ),
        migrations.RemoveField(
            model_name="test",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="badge",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="test",
            name="category",
            field=models.CharField(
                choices=[
                    ("SPRINTS", "Sprints"),
                    ("MIDDLE_DISTANCE", "Middle Distance"),
                    ("LONG_DISTANCE", "Long Distance"),
                    ("JUMPS", "Jumps"),
                    ("THROWS", "Throws"),
                    ("COMBINED_EVENTS", "Combined Events"),
                    ("FREESTYLE", "Freestyle Swimming"),
                    ("BACKSTROKE", "Backstroke Swimming"),
                    ("BREASTSTROKE", "Breaststroke Swimming"),
                    ("BUTTERFLY", "Butterfly Swimming"),
                    ("INDIVIDUAL_MEDLEY", "Individual Medley"),
                ],
                default="SPRINTS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="description",
            field=models.TextField(default="Test Description"),
        ),
        migrations.AddField(
            model_name="test",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="test",
            name="name",
            field=models.CharField(
                default="Test Name",
                help_text="e.g., 100m Sprint, Long Jump",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="unit",
            field=models.CharField(
                default="seconds",
                help_text="e.g., seconds, meters, kilograms",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="badge",
            name="badge_type",
            field=models.CharField(
                choices=[
                    ("PERFORMANCE", "Performance Badge"),
                    ("MILESTONE", "Milestone Badge"),
                    ("PARTICIPATION", "Participation Badge"),
                    ("ACHIEVEMENT", "Achievement Badge"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="id",
            field=models.CharField(
                default=authapp.models.generate_badge_id,
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="id",
            field=models.CharField(
                default=authapp.models.generate_test_id,
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=authapp.models.generate_user_id,
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="Athlete",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=authapp.models.generate_athlete_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=10
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("state", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("address", models.TextField()),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("ATHLETICS", "Athletics"),
                            ("SWIMMING", "Swimming"),
                            ("CYCLING", "Cycling"),
                            ("WEIGHTLIFTING", "Weightlifting"),
                            ("BOXING", "Boxing"),
                            ("WRESTLING", "Wrestling"),
                            ("BADMINTON", "Badminton"),
                            ("TENNIS", "Tennis"),
                            ("FOOTBALL", "Football"),
                            ("BASKETBALL", "Basketball"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SPRINTS", "Sprints"),
                            ("MIDDLE_DISTANCE", "Middle Distance"),
                            ("LONG_DISTANCE", "Long Distance"),
                            ("JUMPS", "Jumps"),
                            ("THROWS", "Throws"),
                            ("COMBINED_EVENTS", "Combined Events"),
                            ("FREESTYLE", "Freestyle"),
                            ("BACKSTROKE", "Backstroke"),
                            ("BREASTSTROKE", "Breaststroke"),
                            ("BUTTERFLY", "Butterfly"),
                            ("INDIVIDUAL_MEDLEY", "Individual Medley"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "profile_image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athlete",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AthleteStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_performances", models.IntegerField(default=0)),
                ("verified_performances", models.IntegerField(default=0)),
                ("pending_performances", models.IntegerField(default=0)),
                ("flagged_performances", models.IntegerField(default=0)),
                ("total_badges", models.IntegerField(default=0)),
                ("total_points", models.IntegerField(default=0)),
                ("current_rank", models.IntegerField(default=0)),
                (
                    "best_performances",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Store best performance for each test",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "athlete",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="authapp.athlete",
                    ),
                ),
            ],
            options={
                "verbose_name": "Athlete Statistics",
                "verbose_name_plural": "Athlete Statistics",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=authapp.models.generate_notification_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("PERFORMANCE_VERIFIED", "Performance Verified"),
                            ("PERFORMANCE_FLAGGED", "Performance Flagged"),
                            ("BADGE_EARNED", "Badge Earned"),
                            ("RANK_CHANGED", "Rank Changed"),
                            ("SYSTEM_UPDATE", "System Update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="authapp.athlete",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=authapp.models.generate_performance_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        help_text="Performance value in the unit specified by test"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("FLAGGED", "Flagged"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "video",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="video"
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("flagged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flag_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUSPICIOUS_TIMING", "Suspicious Timing"),
                            ("TECHNICAL_VIOLATION", "Technical Violation"),
                            ("INVALID_VIDEO", "Invalid Video Evidence"),
                            ("OTHER", "Other Reason"),
                        ],
                        max_length=20,
                    ),
                ),
                ("flag_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="authapp.athlete",
                    ),
                ),
                (
                    "flagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flagged_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="authapp.test",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AthleteBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="authapp.athlete",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="authapp.badge"
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Performance that earned this badge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authapp.performance",
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
            },
        ),
        migrations.DeleteModel(
            name="RecentActivity",
        ),
        migrations.DeleteModel(
            name="UserBadge",
        ),
        migrations.DeleteModel(
            name="UserStats",
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["test", "status"], name="authapp_per_test_id_28fc66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["athlete", "created_at"], name="authapp_per_athlete_50c017_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="athletebadge",
            unique_together={("athlete", "badge")},
        ),
    ]
